//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.08 at 01:40:32 PM IST 
//


package com.tools.dependencyinjection.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DependencyDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DependencyDetail">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="JarName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="JarVersion" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="flag" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DependencyDetail", namespace = "http://com/homedepot/ta/cu/ccs/xmlschema", propOrder = {
    "jarName",
    "jarVersion",
    "flag"
})
public class DependencyDetail {

    @XmlElement(name = "JarName", namespace = "http://com/homedepot/ta/cu/ccs/xmlschema", required = true)
    protected String jarName;
    @XmlElement(name = "JarVersion", namespace = "http://com/homedepot/ta/cu/ccs/xmlschema", required = true)
    protected String jarVersion;
    @XmlElement(namespace = "http://com/homedepot/ta/cu/ccs/xmlschema")
    protected boolean flag;

    /**
     * Gets the value of the jarName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJarName() {
        return jarName;
    }

    /**
     * Sets the value of the jarName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJarName(String value) {
        this.jarName = value;
    }

    /**
     * Gets the value of the jarVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJarVersion() {
        return jarVersion;
    }

    /**
     * Sets the value of the jarVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJarVersion(String value) {
        this.jarVersion = value;
    }

    /**
     * Gets the value of the flag property.
     * 
     */
    public boolean isFlag() {
        return flag;
    }

    /**
     * Sets the value of the flag property.
     * 
     */
    public void setFlag(boolean value) {
        this.flag = value;
    }

	@Override
	public String toString() {
		return "DependencyDetail [jarName=" + jarName + ", jarVersion="
				+ jarVersion + ", flag=" + flag + "]";
	}

}
