//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.08 at 01:40:32 PM IST 
//


package com.tools.dependencyinjection.dto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DependencyInjectionResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DependencyInjectionResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DependencyDetailList" type="{http://com/homedepot/ta/cu/ccs/xmlschema}DependencyDetail" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="XmlString" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DeprecatedDependencyDetaillist" type="{http://com/homedepot/ta/cu/ccs/xmlschema}DeprecatedDependencyDetail" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="FileName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Read" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DependencyInjectionResponse", namespace = "http://com/homedepot/ta/cu/ccs/xmlschema", propOrder = {
    "dependencyDetailLists",
    "xmlString",
    "deprecatedDependencyDetaillists",
    "fileName",
    "read"
})
@XmlRootElement(name = "dependencyInjectionResponse", namespace = "http://com/homedepot/ta/cu/ccs/xmlschema")
public class DependencyInjectionResponse {

    @XmlElement(name = "DependencyDetailList", namespace = "http://com/homedepot/ta/cu/ccs/xmlschema")
    protected List<DependencyDetail> dependencyDetailLists;
    @XmlElement(name = "XmlString", namespace = "http://com/homedepot/ta/cu/ccs/xmlschema", required = true)
    protected String xmlString;
    @XmlElement(name = "DeprecatedDependencyDetaillist", namespace = "http://com/homedepot/ta/cu/ccs/xmlschema")
    protected List<DeprecatedDependencyDetail> deprecatedDependencyDetaillists;
    @XmlElement(name = "FileName", namespace = "http://com/homedepot/ta/cu/ccs/xmlschema", required = true)
    protected String fileName;
    @XmlElement(name = "Read", namespace = "http://com/homedepot/ta/cu/ccs/xmlschema", required = true)
    protected String read;

    /**
     * Gets the value of the dependencyDetailLists property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dependencyDetailLists property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDependencyDetailLists().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DependencyDetail }
     * 
     * 
     */
    public List<DependencyDetail> getDependencyDetailLists() {
        if (dependencyDetailLists == null) {
            dependencyDetailLists = new ArrayList<DependencyDetail>();
        }
        return this.dependencyDetailLists;
    }

    /**
     * Gets the value of the xmlString property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlString() {
        return xmlString;
    }

    /**
     * Sets the value of the xmlString property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlString(String value) {
        this.xmlString = value;
    }

    /**
     * Gets the value of the deprecatedDependencyDetaillists property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deprecatedDependencyDetaillists property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeprecatedDependencyDetaillists().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeprecatedDependencyDetail }
     * 
     * 
     */
    public List<DeprecatedDependencyDetail> getDeprecatedDependencyDetaillists() {
        if (deprecatedDependencyDetaillists == null) {
            deprecatedDependencyDetaillists = new ArrayList<DeprecatedDependencyDetail>();
        }
        return this.deprecatedDependencyDetaillists;
    }

    /**
     * Gets the value of the fileName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * Sets the value of the fileName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFileName(String value) {
        this.fileName = value;
    }

    /**
     * Gets the value of the read property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRead() {
        return read;
    }

    /**
     * Sets the value of the read property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRead(String value) {
        this.read = value;
    }

	@Override
	public String toString() {
		return "DependencyInjectionResponse [dependencyDetailLists="
				+ dependencyDetailLists + ", xmlString=" + xmlString
				+ ", deprecatedDependencyDetaillists="
				+ deprecatedDependencyDetaillists + ", fileName=" + fileName
				+ ", read=" + read + "]";
	}

}
