//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.08 at 01:40:32 PM IST 
//


package com.tools.dependencyinjection.dto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DependencyInjectionRequest complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DependencyInjectionRequest">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AppName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ProjectPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="deprecatedJarListPath" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DependencyInjectionRequest", namespace = "http://com/homedepot/ta/cu/ccs/xmlschema", propOrder = {
    "appName",
    "projectPath",
    "deprecatedJarListPath"
})
@XmlRootElement(name = "dependencyInjectionRequest", namespace = "http://com/homedepot/ta/cu/ccs/xmlschema")
public class DependencyInjectionRequest {

    @XmlElement(name = "AppName", namespace = "http://com/homedepot/ta/cu/ccs/xmlschema", required = true)
    protected String appName;
    @XmlElement(name = "ProjectPath", namespace = "http://com/homedepot/ta/cu/ccs/xmlschema", required = true)
    protected String projectPath;
    @XmlElement(namespace = "http://com/homedepot/ta/cu/ccs/xmlschema", required = true)
    protected String deprecatedJarListPath;

    /**
     * Gets the value of the appName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAppName() {
        return appName;
    }

    /**
     * Sets the value of the appName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAppName(String value) {
        this.appName = value;
    }

    /**
     * Gets the value of the projectPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProjectPath() {
        return projectPath;
    }

    /**
     * Sets the value of the projectPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProjectPath(String value) {
        this.projectPath = value;
    }

    /**
     * Gets the value of the deprecatedJarListPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeprecatedJarListPath() {
        return deprecatedJarListPath;
    }

    /**
     * Sets the value of the deprecatedJarListPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeprecatedJarListPath(String value) {
        this.deprecatedJarListPath = value;
    }

	@Override
	public String toString() {
		return "DependencyInjectionRequest [appName=" + appName
				+ ", projectPath=" + projectPath + ", deprecatedJarListPath="
				+ deprecatedJarListPath + "]";
	}
    

}
