//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.05.28 at 12:59:58 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com/homedepot/ta/cu/ccs/xmlschema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.tools.dependencyinjection.dto;

