//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.1-b02-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.07.06 at 01:58:15 PM IST 
//


package com.tools.dependencyinjection.dto;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReadFileResponse complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ReadFileResponse">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ReadFileList" type="{http://com/homedepot/ta/cu/ccs/xmlschema}ReadFile" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ReadFileResponse", namespace = "http://com/homedepot/ta/cu/ccs/xmlschema", propOrder = {
    "readFileLists"
})
@XmlRootElement(name = "readFileResponse", namespace = "http://com/homedepot/ta/cu/ccs/xmlschema")
public class ReadFileResponse {

    @XmlElement(name = "ReadFileList", namespace = "http://com/homedepot/ta/cu/ccs/xmlschema")
    protected List<ReadFile> readFileLists;

    /**
     * Gets the value of the readFileLists property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the readFileLists property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReadFileLists().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReadFile }
     * 
     * 
     */
    public List<ReadFile> getReadFileLists() {
        if (readFileLists == null) {
            readFileLists = new ArrayList<ReadFile>();
        }
        return this.readFileLists;
    }

}
